version: "3.9"

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672

  redis:
    image: "redis:7.2.4"
    container_name: redis
    ports:
      - 6379:6379

  worker:
    #image: registry.gitlab.secpriv.tuwien.ac.at/secpriv/systemsec/webview-injection/merger-worker:1.0.2
    build: .
    environment: &env
      - RABBITMQ_USER=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APK_DIR=/apks
      - RES_DIR=/results
      - APK_JSON_PATH=/apks.json
      - MERGED_APK_DIR=/merged_apks
    command: ['celery', '-A', 'proj', 'worker', '-l', 'INFO', '-f', '/logs/celery.logs', '--concurrency=${CONCURRENCY}']
    volumes:
      - ${APK_DIR}:/apks:ro
      - ${APK_JSON_PATH}:/apks.json
      - ${LOGS_PATH}:/logs
      - ${MERGED_APK_DIR}:/merged_apks
      - ${RES_DIR}:/results
    depends_on:
      - rabbitmq
      - redis

  flower:
    image: mher/flower:1.2.0
    environment:
      CELERY_BROKER_URL: pyamqp://guest@rabbitmq:5672
      CELERY_BACKEND_URL: redis://redis:6379
    ports:
      - 5050:5555
    depends_on:
      - rabbitmq
      - redis

  analyser:
    #image: registry.gitlab.secpriv.tuwien.ac.at/secpriv/systemsec/webview-injection/merger-worker:1.0.2
    build: .
    environment: *env
    command: ['python', 'analyser.py']
    volumes:
      - ${APK_JSON_PATH}:/apks.json
    restart: 'no'
    profiles:
      - init